#!/bin/bash

# PYENV_HOME=$WORKSPACE/.myvenv
PYENV_HOME=$WORKSPACE/myvenv

# Delete previously built virtualenv
if [ -d $PYENV_HOME ]; then
    rm -rf $PYENV_HOME
fi

# Create virtualenv and install packages
python3 -m venv $PYENV_HOME
. $PYENV_HOME/bin/activate
pip install -r requirements.txt

# Tests, style and violations checker
#py.test --cov
py.test --junitxml=output.xml
#pylint -f parseable app.py | tee pylint.out
#pep8 app.py > pep8_report.txt